### ISSUE TITLE
[Bug]: Name of the VSS Spec is hardcoded to vspec.json for K3D configmap

### ISSUE THREAD

**Issue by MP91** [eclipse-velocitas/devenv-runtimes#55]
### Severity

Critical

### What release version, tag or commit-hash did you use?

v2.2.4

### Current Behavior

If one has a custom vspec with a different name than vspec.json, the databroker in the K3D runtime fails to start due a hardcoded value in the helm-charts for the databroker.

### Steps to Reproduce

- create a vss.json in the app-directory
- adapt appmanifest
- regenerate model
- start k3d runtime up
- databroker fails to start due to missing configmap

### Expected Behavior

details are taken from the appmanifest and are not hardcoded

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by BjoernAtBosch** [comment]
Not relevant any longer since we removed support for Dapr middleware and K3D runtime.
Related issues:
https://github.com/eclipse-velocitas/vehicle-app-python-template/issues/233
https://github.com/eclipse-velocitas/vehicle-app-cpp-template/issues/92
https://github.com/eclipse-velocitas/vehicle-app-template/issues/10
https://github.com/eclipse-velocitas/vehicle-app-python-sdk/issues/121
https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/issues/85
https://github.com/eclipse-velocitas/devenv-devcontainer-setup/issues/59
https://github.com/eclipse-velocitas/devenv-runtimes/issues/68
https://github.com/eclipse-velocitas/devenv-github-workflows/issues/52
